version: "3"

services:
  quakeledger-staging:
    image: gfzriesgos/quakeledger:latest

  shakyground-staging:
    image: gfzriesgos/shakyground:latest

  assetmaster-staging:
    image: gfzriesgos/assetmaster:latest

  modelprop-staging:
    image: gfzriesgos/modelprop:latest

  deus-staging:
    image: gfzriesgos/deus:latest

  flooddamage-staging:
    image: gfzriesgos/flooddamage:latest

  eve-staging:
    image: gfzriesgos/eve:latest

  riesgos-wps-staging:
    image: gfzriesgos/riesgos-wps:latest
    container_name: riesgos-wps-staging
    restart: always
    environment:
      - CATALINA_OPTS=-Xmx4g -Xms4g
      - RIESGOS_MAX_CACHE_SIZE_MB=1024
      - RIESGOS_GEOSERVER_ACCESS_BASE_URL=__GEOSERVER_URL__
      - RIESGOS_GEOSERVER_SEND_BASE_URL=http://riesgos-wps-staging:8080/geoserver
      - RIESGOS_GEOSERVER_USERNAME=admin
      - RIESGOS_GEOSERVER_PASSWORD=__GEOSERVER_PASSWORD__
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "riesgos-json-config-staging:/usr/share/riesgos/json-configurations"
      - "riesgos-wps-hsqldb-staging:/usr/local/tomcat/webapps/wps/WEB-INF/classes/db/data"
      - "riesgos-wps-logs-staging:/usr/local/tomcat/logs"
      - "/builds/riesgos-assistance-staging/tomcat-users-staging.xml:/usr/local/tomcat/conf/tomcat-users.xml"
      - "/builds/riesgos-assistance-staging/users-staging.xml:/usr/local/tomcat/webapps/geoserver/data/security/usergroup/default/users.xml"
      - "/builds/riesgos-assistance-staging/application_properties_staging.js:/usr/local/tomcat/webapps/wps-js-client/application_properties.js"
      - "/builds/riesgos-assistance-staging/server.xml:/usr/local/tomcat/conf/server.xml"

  nginx:
    image: nginx:1.21.6-alpine
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "/etc/ssl/private/rz-vm140.gfz-potsdam.de.key:/etc/ssl/private/rz-vm140.gfz-potsdam.de.key:ro"
      - "/etc/ssl/private/rz-vm140.gfz-potsdam.de.pem:/etc/ssl/private/rz-vm140.gfz-potsdam.de.pem:ro"
      - "/etc/ssl/dhparam.pem:/etc/ssl/dhparam.pem:ro"
      - "/etc/ssl/dfn-ca-global-g2-chain.pem:/etc/ssl/chain.pem:ro"
      - "/builds/riesgos-assistance-staging/nginx_staging.conf:/etc/nginx/conf.d/default.conf:ro"

volumes:
  riesgos-json-config-staging:
  riesgos-wps-hsqldb-staging:
  riesgos-wps-logs-staging:
